/* AERA FLORIA - part manifest for the technical animation.
   Geometry: 1,410,324 triangles, full topology (meshopt-compressed, NOT decimated).
   All values are in NORMALISED WORLD UNITS (same space Three.js renders in),
   so 'travel' can be added straight to a part's position.y.
   'travel' comes from a collision-free stack solver - the parts interpenetrate
   in the source (heights sum to 2.2x the assembled height), so a uniform
   rank-based ladder cannot separate them.
   Generated by make_layout.py; do not hand-edit numbers. */
window.AERA_PARTS = {
 "unit": "world",
 "S": 144.52765733806334,
 "H": 3.3,
 "GAP": 0.231,
 "explodedH": 10.045209827880699,
 "parts": [
  {
   "name": "Cylinder001",
   "label": "Công tắc điện",
   "color": "#FF6B6B",
   "ghost": false,
   "tris": 3068,
   "rank": 0,
   "y": -1.286657469452109,
   "cy": -1.286657469452109,
   "h": 0.12429378531073447,
   "ext": [
    0.5529628169754304,
    0.12429378531073447,
    0.5564314807515438
   ],
   "travel": 0.0
  },
  {
   "name": "part_12",
   "label": "Đế chân / chân đứng",
   "color": "#B8C0CC",
   "ghost": false,
   "tris": 1188,
   "rank": 1,
   "y": -1.2304362107476023,
   "cy": -1.2304362107476023,
   "h": 0.8391275785047958,
   "ext": [
    2.178754434371305,
    0.8391275785047958,
    1.787084482985153
   ],
   "travel": 0.6564894232032585
  },
  {
   "name": "Layer_Layer_1",
   "label": "Lớp mạch điện (PCB)",
   "color": "#6EE7A8",
   "ghost": false,
   "tris": 9004,
   "rank": 2,
   "y": -1.1721915648403627,
   "cy": -1.1721915648403627,
   "h": 0.14250427013533043,
   "ext": [
    0.04581526737616608,
    0.14250427013533043,
    0.21780317960846146
   ],
   "travel": 1.320060701616082
  },
  {
   "name": "polySurface15_pCylinder001aaaa",
   "label": "Chân đế in 3D",
   "color": "#4361EE",
   "ghost": false,
   "tris": 301794,
   "rank": 3,
   "y": -0.7750295624753647,
   "cy": -0.7750295624753647,
   "h": 1.3037839968466693,
   "ext": [
    1.2656286953094205,
    1.3037839968466693,
    1.2682301931415056
   ],
   "travel": 1.8770428327420838
  },
  {
   "name": "part_11",
   "label": "Ống khuếch tán sáng",
   "color": "#9BE8FF",
   "ghost": true,
   "tris": 275624,
   "rank": 4,
   "y": -0.4478189462619892,
   "cy": -0.4478189462619892,
   "h": 0.9431874917882013,
   "ext": [
    0.5411115490737091,
    0.9431874917882013,
    0.5421232426750756
   ],
   "travel": 2.9043179608461434
  },
  {
   "name": "polySurface15_pCylinder7",
   "label": "Căng cân tích (cage)",
   "color": "#4CC9F0",
   "ghost": true,
   "tris": 71550,
   "rank": 5,
   "y": -0.3303179608461438,
   "cy": -0.3303179608461438,
   "h": 0.413060044672185,
   "ext": [
    0.5947313099461305,
    0.413060044672185,
    0.5947313099461305
   ],
   "travel": 3.695940743660491
  },
  {
   "name": "Base_2",
   "label": "Vòng đệm silicone",
   "color": "#F1FAEE",
   "ghost": false,
   "tris": 163,
   "rank": 6,
   "y": -0.3032912889239259,
   "cy": -0.3032912889239259,
   "h": 0.045526212061489955,
   "ext": [
    0.17242149520430958,
    0.045526212061489955,
    0.16519511233740639
   ],
   "travel": 4.12920720010511
  },
  {
   "name": "polySurface10_group1",
   "label": "Nắp trên + ren thông gió",
   "color": "#C77DFF",
   "ghost": false,
   "tris": 105564,
   "rank": 7,
   "y": -0.2326172644856129,
   "cy": -0.2326172644856129,
   "h": 0.30220733149389045,
   "ext": [
    1.921350676652214,
    0.30220733149389045,
    1.921350676652214
   ],
   "travel": 4.463399947444488
  },
  {
   "name": "Base",
   "label": "Đầu ren ren thông gió",
   "color": "#00C2A8",
   "ghost": false,
   "tris": 2941,
   "rank": 8,
   "y": -0.13188148732098282,
   "cy": -0.13188148732098282,
   "h": 0.2546577322296676,
   "ext": [
    0.28761003810274605,
    0.2546577322296676,
    0.2754697148863487
   ],
   "travel": 4.872096702141636
  },
  {
   "name": "Bulb",
   "label": "Móc treo / contact",
   "color": "#F94144",
   "ghost": false,
   "tris": 94,
   "rank": 9,
   "y": -0.022907633688083132,
   "cy": -0.022907633688083132,
   "h": 0.020089344369990804,
   "ext": [
    0.32128498226251484,
    0.020089344369990804,
    0.3075548548153988
   ],
   "travel": 5.131496386808566
  },
  {
   "name": "Bulb_3",
   "label": "Đầu bóng E27",
   "color": "#FFB020",
   "ghost": false,
   "tris": 320,
   "rank": 10,
   "y": 0.2313165155695703,
   "cy": 0.2313165155695703,
   "h": 0.43112600183944294,
   "ext": [
    0.6606359216922876,
    0.43112600183944294,
    0.6324530285113651
   ],
   "travel": 5.333879910655629
  },
  {
   "name": "group1_polySurface9",
   "label": "Vỏ ngoài lưới (lattice)",
   "color": "#7C9BFF",
   "ghost": true,
   "tris": 638086,
   "rank": 11,
   "y": 0.6396071475495994,
   "cy": 0.6396071475495994,
   "h": 2.0207857049008013,
   "ext": [
    2.786348705820523,
    2.0207857049008013,
    2.7853370122191565
   ],
   "travel": 6.382545132045722
  },
  {
   "name": "Bulb_2",
   "label": "Bóng đèn — thân kính",
   "color": "#FFE066",
   "ghost": false,
   "tris": 928,
   "rank": 12,
   "y": 0.643653921955065,
   "cy": 0.643653921955065,
   "h": 0.43286033372749966,
   "ext": [
    0.6954670871107608,
    0.43286033372749966,
    0.6659834450137959
   ],
   "travel": 7.836321376954408
  }
 ]
};
